
const country_codes = {
  "AF" : "Afghanistan", "AX" : "Aland Islands", "AL" : "Albania",
  "DZ" : "Algeria", "AS" : "American Samoa", "AD" : "Andorra",
  "AO" : "Angola", "AI" : "Anguilla", "AQ" : "Antarica",
  "AG" : "Antigua and Barbuda", "AR" : "Argentina", "AM" : "Armenia",
  "AU" : "Australia", "AT" : "Austria", "AZ" : "Azerbaijan", 
  "BS" : "The Bahamas", "BH" : "Bahrain", "BD" : "Bangladesh", 
  "BB" : "Barbados", "BY" : "Belarus", "BE" : "Belgium", 
  "BZ" : "Belize", "BJ" : "Benin", "BT" : "Bhutan", 
  "BO" : "Bolivia", "BQ" : "Bonaire, Sint Eustatius and Saba", 
  "BA" : "Bosnia and Herzegovina", "BW" : "Botswana", "BV" : "Bouvet Island", 
  "BR" : "Brazil", "IO" : "British Indian Ocean Territory", 
  "BN" : "Brunei", "BG" : "Bulgaria", "BF" : "Burkina Faso", 
  "BI" : "Burundi", "CV" : "Cabo Verde (Cape Verde)", "KH" : "Cambodia", 
  "CM" : "Cameroon", "CA" : "Canada", "CF" : "Central African Republic", 
  "TD" : "Chad", "CL" : "Chile", "CN" : "China", 
  "CX" : "Christmas Island", "CC" : "Cocos (Keeling) Islands", "CO" : "Colombia", 
  "KM" : "Comoros", "CD" : "Congo, Democratic Republic of the", 
  "CG" : "Congo, Republic of the", "CK" : "Cook Islands", "CR" : "Costa Rica", 
  "CI" : "Côte d’Ivoire (Ivory Coast)", "HR" : "Croatia", "CU" : "Cuba", 
  "CW" : "Curaçao", "CY" : "Cyprus", "CZ" : "Czech Republic (Czechia)", 
  "DK" : "Denmark", "DJ" : "Djibouti", "DM" : "Dominica", 
  "DO" : "Dominican Republic", "TL" : "East Timor (Timor-Leste)", "EC" : "Ecuador", 
  "EG" : "Egypt", "SV" : "El Salvador", "GQ" : "Equatorial Guinea", 
  "ER" : "Eritrea", "EE" : "Estonia", "SZ" : "Eswatini", 
  "ET" : "Ethiopia", "FO" : "Faroe Islands", "FK" : "Falkland Islands (Malvinas)", 
  "FJ" : "Fiji", "FI" : "Finland", "FR" : "France", 
  "GF" : "French Guiana", "TF" : "French Southern Territories", 
  "PF" : "French Polynesia", "GA" : "Gabon", "GM" : "Gambia", 
  "GE" : "Georgia", "DE" : "Germany", "GH" : "Ghana", 
  "GI" : "Gibraltar", "GR" : "Greece", "GL" : "Greenland", 
  "GD" : "Grenada", "GP" : "Guadeloupe", "GU" : "Guam", 
  "GT" : "Guatemala", "GG" : "Guernsey", "GN" : "Guinea", 
  "GW" : "Guinea-Bissau", "GY" : "Guyana", "HT" : "Haiti", 
  "HM" : "Heard Island and McDonald Islands", "HN" : "Honduras", "HK" : "Hong Kong", 
  "HU" : "Hungary", "IS" : "Iceland", "IN" : "India", 
  "ID" : "Indonesia", "IR" : "Iran", "IQ" : "Iraq", 
  "IE" : "Ireland", "IM" : "Isle of Man", "IL" : "Israel", 
  "IT" : "Italy", "JM" : "Jamaica", "JP" : "Japan", 
  "JE" : "Jersey", "JO" : "Jordan", "KZ" : "Kazakhstan", 
  "KE" : "Kenya", "KI" : "Kiribati", "KP" : "Korea, North", 
  "KR" : "Korea, South", "XK" : "Kosovo", "KW" : "Kuwait", 
  "KG" : "Kyrgyzstan", "LA" : "Laos", "LV" : "Latvia", 
  "LB" : "Lebanon", "LS" : "Lesotho", "LR" : "Liberia", 
  "LY" : "Libya", "LI" : "Liechtenstein", "LT" : "Lithuania", 
  "LU" : "Luxembourg", "MO" : "Macao", "MG" : "Madagascar", 
  "MW" : "Malawi", "MY" : "Malaysia", "MV" : "Maldives", 
  "ML" : "Mali", "MT" : "Malta", "MQ" : "Martinique", 
  "MH" : "Marshall Islands", "YT" : "Mayotte", "MR" : "Mauritania", 
  "MU" : "Mauritius", "MX" : "Mexico", "FM" : "Micronesia, Federated States of", 
  "MD" : "Moldova", "MC" : "Monaco", "MN" : "Mongolia", 
  "ME" : "Montenegro", "MS" : "Montserrat", "MA" : "Morocco", 
  "MZ" : "Mozambique", "MM" : "Myanmar (Burma)", "NA" : "Namibia", 
  "NR" : "Nauru", "NP" : "Nepal", "NL" : "Netherlands", 
  "AN" : "Netherlands Antilles", "NC" : "New Caledonia", "NZ" : "New Zealand", 
  "NI" : "Nicaragua", "NE" : "Niger", "NG" : "Nigeria", 
  "NU" : "Niue", "NF" : "Norfolk Island", "MK" : "North Macedonia", 
  "MP" : "Northern Mariana Islands", "NO" : "Norway", "OM" : "Oman", 
  "PK" : "Pakistan", "PW" : "Palau", "PS" : "Palestinian Territory", 
  "PA" : "Panama", "PG" : "Papua New Guinea", "PY" : "Paraguay", 
  "PE" : "Peru", "PH" : "Philippines", "PN" : "Pitcairn Islands", 
  "PL" : "Poland", "PT" : "Portugal", "PR" : "Puerto Rico", 
  "QA" : "Qatar", "RE" : "Reunion", "RO" : "Romania", 
  "RU" : "Russia", "RW" : "Rwanda", "BL" : "Saint Barthelemy", 
  "KN" : "Saint Kitts and Nevis", 
  "SH" : "Saint Helena, Ascension and Tristan da Cunha", 
  "LC" : "Saint Lucia", "MF" : "Saint Martin", "PM" : "Saint Pierre and Miquelon", 
  "VC" : "Saint Vincent and the Grenadines", "WS" : "Samoa", "SM" : "San Marino", 
  "ST" : "Sao Tome and Principe", "SA" : "Saudi Arabia", "SN" : "Senegal", 
  "RS" : "Serbia", "SC" : "Seychelles", "SL" : "Sierra Leone", 
  "SG" : "Singapore", "SX" : "Sint Maarten (Netherlands)", "SK" : "Slovakia", 
  "SI" : "Slovenia", "SB" : "Solomon Islands", "SO" : "Somalia", 
  "ZA" : "South Africa", "GS" : "South Georgia and the South Sandwich Islands", 
  "ES" : "Spain", "LK" : "Sri Lanka", "SD" : "Sudan", 
  "SS" : "Sudan, South", "SR" : "Suriname", "SJ" : "Svalbard & Jan Mayen Islands", 
  "SE" : "Sweden", "CH" : "Switzerland", "SY" : "Syria", 
  "TW" : "Taiwan", "TJ" : "Tajikistan", "TZ" : "Tanzania", 
  "TH" : "Thailand", "TG" : "Togo", "TK" : "Tokelau", 
  "TO" : "Tonga", "TT" : "Trinidad and Tobago", "TN" : "Tunisia", 
  "TR" : "Turkey", "TM" : "Turkmenistan", "TC" : "Turks and Caicos Islands", 
  "TV" : "Tuvalu", "UG" : "Uganda", "UA" : "Ukraine", 
  "AE" : "United Arab Emirates", "GB" : "United Kingdom", "US" : "United States", 
  "UM" : "United States Minor Outlying Islands", 
  "VI" : "United States Virgin Islands", "UY" : "Uruguay", "UZ" : "Uzbekistan", 
  "VU" : "Vanuatu", "VA" : "Vatican City", "VE" : "Venezuela", 
  "VN" : "Vietnam", "WF" : "Wallis and Futuna", "EH" : "Western Sahara", 
  "YE" : "Yemen", "ZM" : "Zambia", "ZW" : "Zimbabwe",
 };

export function countryCodes(code){
  return country_codes[code];
}